name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          output_format: json # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
          output_file_path: snyk.json
          download_external_modules: true
          soft_fail: true # optional: do not return an error code if there are failed checks
          framework: terraform

      - name: Upload Json as artifact
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report
          path: snyk.json

  iac-dd-scan:
    runs-on: ubuntu-latest
    needs: checkov-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Display downloaded files
        run: ls

      - name: Download SARIF report artifact
        uses: actions/download-artifact@v2
        with:
          name: snyk-report
          path: .

      - name: Display downloaded files
        run: ls

      - name: Use JSON from SARIF
        run: |
          mkdir -p ./reports
          mv results_json.json ./reports/snyk.json

      - name: Publish report
        id: import-scan
        uses: ivanamat/defectdojo-import-scan@v1
        with:
          token: ${{ secrets.DEFECTDOJO_TOKEN }}
          defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
          file: reports/snyk.json
          scan_type: Checkov Scan
          engagement: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
          push_to_jira: true

      - name: Show response
        run: |
          set -e
          printf '%s\n' '${{ steps.import-scan.outputs.response }}'
