name: Build
on:
  push:
    branches:
      - testing
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check Kubernetes manifest file for issues
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     args: --json > snyk.json

      # - name: Ensure Json file exists
      #   run: ls -al

      # - name: Upload Json as artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: snyk-report
      #     path: snyk.json

  iac-dd-scan:
    runs-on: ubuntu-latest
    needs: iac
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download SARIF report artifact
        uses: actions/download-artifact@v2
        with:
          name: semgrep-report
          path: .

      - name: Display downloaded files
        run: ls

      - name: Use JSON from SARIF
        run: |
          mkdir -p ./reports
          mv snyk.json ./reports/snyk.json

      - name: Publish report
        id: import-scan
        uses: ivanamat/defectdojo-import-scan@v1
        with:
          token: ${{ secrets.DEFECTDOJO_TOKEN }}
          defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
          file: reports/snyk.json
          scan_type: Semgrep JSON Report
          engagement: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
          push_to_jira: true

      - name: Show response
        run: |
          set -e
          printf '%s\n' '${{ steps.import-scan.outputs.response }}'
