name: Build
on:
  push:
    branches:
      - testing

jobs:
  kics-scan:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Scan Iac with kics
      - name: run kics Scan
        uses: checkmarx/kics-github-action@v1.7.0
        with:
          # scanning 1 directories: "./eks"
          path: "eks"
          ignore_on_exit: results
          output_path: .
      # Display the results in json format
      - name: display kics results
        run: |
          cat results.json

      - name: Upload Json as artifact
        uses: actions/upload-artifact@v2
        with:
          name: kicks-report
          path: results.json

  iac-dd-scan:
    runs-on: ubuntu-latest
    needs: kics-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download json report artifact
        uses: actions/download-artifact@v2
        with:
          name: kicks-report
          path: .

      - name: Use JSON from SARIF
        run: |
          mkdir -p ./reports
          mv results.json ./reports/results.json

      - name: Publish report
        id: import-scan
        uses: ivanamat/defectdojo-import-scan@v1
        with:
          token: ${{ secrets.DEFECTDOJO_TOKEN }}
          defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
          file: reports/results.json
          scan_type: KICS Scan
          engagement: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
          push_to_jira: true

      - name: Show final response output
        run: |
          set -e
          printf '%s\n' '${{ steps.import-scan.outputs.response }}'
